"""
This type stub file was generated by pyright.
"""

from ckan import plugins

''' THIS PLUGIN IS FOR TESTING PURPOSES ONLY.
Currently this is used in tests/functional/test_tag_vocab.py'''
TEST_VOCAB_NAME = 'test-vocab'
class MockVocabTagsPlugin(plugins.SingletonPlugin):
    def is_fallback(self):
        ...
    
    def package_types(self):
        ...
    
    def new_template(self):
        ...
    
    def edit_template(self):
        ...
    
    def search_template(self):
        ...
    
    def read_template(self):
        ...
    
    def package_form(self):
        ...
    
    def setup_template_variables(self, context, data_dict=...):
        ...
    
    def create_package_schema(self):
        ...
    
    def update_package_schema(self):
        ...
    
    def show_package_schema(self):
        ...
    


