from ckan.logic.validators import Validator
from typing import (
    Callable,
    Dict,
    Iterable,
)

Schema = Dict[str, Iterable[Validator]]

ComplexSchemaFunc = Callable[..., Schema]

PlainSchemaFunc = Callable[[], Schema]

def validator_args(fn: ComplexSchemaFunc) -> PlainSchemaFunc: ...
def default_resource_schema() -> Schema: ...
def default_update_resource_schema() -> Schema: ...
def default_tags_schema() -> Schema: ...
def default_create_tag_schema() -> Schema: ...
def default_create_package_schema() -> Schema: ...
def default_update_package_schema() -> Schema: ...
def default_show_package_schema() -> Schema: ...
def default_group_schema() -> Schema: ...
def group_form_schema() -> Schema: ...
def default_update_group_schema() -> Schema: ...
def default_show_group_schema() -> Schema: ...
def default_extras_schema() -> Schema: ...
def default_relationship_schema() -> Schema: ...
def default_create_relationship_schema() -> Schema: ...
def default_update_relationship_schema() -> Schema: ...
def default_user_schema() -> Schema: ...
def user_new_form_schema() -> Schema: ...
def user_edit_form_schema() -> Schema: ...
def default_update_user_schema() -> Schema: ...
def default_generate_apikey_user_schema() -> Schema: ...
def default_user_invite_schema() -> Schema: ...
def default_task_status_schema() -> Schema: ...
def default_vocabulary_schema() -> Schema: ...
def default_create_vocabulary_schema() -> Schema: ...
def default_update_vocabulary_schema() -> Schema: ...
def default_create_activity_schema() -> Schema: ...
def default_follow_user_schema() -> Schema: ...
def default_follow_dataset_schema() -> Schema: ...
def member_schema() -> Schema: ...
def default_follow_group_schema() -> Schema: ...
def default_package_list_schema() -> Schema: ...
def default_pagination_schema() -> Schema: ...
def default_dashboard_activity_list_schema() -> Schema: ...
def default_activity_list_schema() -> Schema: ...
def default_autocomplete_schema() -> Schema: ...
def default_package_search_schema() -> Schema: ...
def default_resource_search_schema() -> Schema: ...
def create_schema_for_required_keys(keys): ...
def default_create_resource_view_schema(resource_view): ...
def default_create_resource_view_schema_unfiltered() -> Schema: ...
def default_create_resource_view_schema_filtered() -> Schema: ...
def default_update_resource_view_schema(resource_view): ...
def default_update_resource_view_schema_changes() -> Schema: ...
def default_update_configuration_schema() -> Schema: ...
def update_configuration_schema(): ...
def job_list_schema() -> Schema: ...
def job_clear_schema() -> Schema: ...
def default_create_api_token_schema() -> Schema: ...
def package_revise_schema() -> Schema: ...
