"""
This type stub file was generated by pyright.
"""

import logging

log = logging.getLogger(__name__)
_config_encode_secret = u"api_token.jwt.encode.secret"
_config_decode_secret = u"api_token.jwt.decode.secret"
_config_secret_fallback = u"beaker.session.secret"
_config_algorithm = u"api_token.jwt.algorithm"
def into_seconds(dt):
    ...

def get_schema():
    ...

def postprocess(data, jti, data_dict):
    ...

def decode(encoded, **kwargs):
    ...

def encode(data, **kwargs):
    ...

def add_extra(result):
    ...

def get_user_from_token(token, update_access_time=...):
    ...

