from datetime import datetime
from typing import Any, Dict, Optional
import ckan.model as model

def into_seconds(dt: datetime) -> int: ...
def get_schema() -> Dict: ...
def postprocess(data: Dict, jti: str, data_dict: Dict) -> Dict: ...
def decode(encoded: str, **kwargs: Any) -> Optional[Dict]: ...
def encode(data: Dict, **kwargs: Any) -> str: ...
def add_extra(result: Dict) -> Dict: ...
def get_user_from_token(
    token: str, update_access_time: bool = ...
) -> Optional[model.User]: ...
