from typing import Dict, Tuple

DEFAULT_MAIN_CSS_FILE: str
mappings: Dict
app_globals_from_config_details: Dict

def set_main_css(css_file: str) -> None: ...
def set_app_global(key: str, value: str) -> None: ...
def process_app_global(key: str, value: str) -> Tuple[str, str]: ...
def get_globals_key(key: str) -> str: ...
def reset() -> None: ...

class _Globals(object): ...

app_globals: _Globals
