"""
This type stub file was generated by pyright.
"""

import logging

'''
Functions for generating a list of differences between two versions of a
dataset
'''
log = logging.getLogger(__name__)
def check_resource_changes(change_list, old, new, old_activity_id):
    '''
    Compares two versions of a dataset and records the changes between them
    (just the resources) in change_list. e.g. resources that are added, changed
    or deleted. For existing resources, checks whether their names, formats,
    and/or descriptions have changed, as well as whether the url changed (e.g.
    a new file has been uploaded for the resource).
    '''
    ...

def check_metadata_changes(change_list, old, new):
    '''
    Compares two versions of a dataset and records the changes between them
    (excluding resources) in change_list.
    '''
    ...

