"""
This type stub file was generated by pyright.
"""

import logging
from ckan.common import config

log = logging.getLogger(__name__)
def min_path(path):
    '''Return the .min.* filename for the given .js or .css file.

    For example moo.js -> moo.min.js

    '''
    ...

def create_library(name, path, depend_base=...):
    ''' Creates a fanstatic library `name` with the contents of a
    directory `path` using resource.config if found.'''
    ...

public = config.get('ckan.base_public_folder')
base_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', public, 'base'))
