import datetime
from typing import Optional

def localised_nice_date(
    datetime_: datetime.datetime,
    show_date: bool = ...,
    with_hours: bool = ...,
    with_seconds: bool = ...,
    format: Optional[str] = ...,
) -> str: ...
def localised_number(number: int) -> str: ...
def localised_filesize(number: int) -> str: ...
def localised_SI_number(number: int) -> str: ...
