from typing import Any, Dict, Optional
from markupsafe import Markup

def get_jinja_env_options() -> Dict: ...
def empty_and_escape(value: Optional[str]) -> Markup: ...
def regularise_html(html: Optional[str]) -> Optional[str]: ...
def jinja2_getattr(self, obj: Any, attribute: str) -> Any: ...
