
import logging

log = logging.getLogger(__name__)

class MailerException(Exception): ...

def mail_recipient(
    recipient_name, recipient_email, subject, body, body_html=..., headers=...
):
    ...

def mail_user(recipient, subject, body, body_html=..., headers=...):
    ...

def get_reset_link_body(user): ...
def get_invite_body(user, group_dict=..., role=...): ...
def get_reset_link(user): ...
def send_reset_link(user): ...
def send_invite(user, group_dict=..., role=...): ...
def create_reset_key(user): ...
def make_key(): ...
def verify_reset_link(user, key): ...
