from ckan.model.user import User
from typing import Dict, Optional

class MailerException(Exception): ...

def mail_recipient(
    recipient_name: str,
    recipient_email: str,
    subject: str,
    body: str,
    body_html: Optional[str] = ...,
    headers: Dict = ...,
) -> None: ...
def mail_user(
    recipient: str,
    subject: str,
    body: str,
    body_html: Optional[str] = ...,
    headers: Dict = ...,
) -> None: ...
def get_reset_link_body(user: User) -> str: ...
def get_invite_body(
    user: User, group_dict: Optional[Dict] = ..., role: Optional[str] = ...
) -> str: ...
def get_reset_link(user: User) -> str: ...
def send_reset_link(user: User) -> None: ...
def send_invite(user: User, group_dict=..., role=...) -> None: ...
def create_reset_key(user: User) -> None: ...
def make_key() -> str: ...
def verify_reset_link(user: User, key: Optional[str]) -> bool: ...
