"""
This type stub file was generated by pyright.
"""

MAX_FILENAME_EXTENSION_LENGTH = 21
MAX_FILENAME_TOTAL_LENGTH = 100
MIN_FILENAME_TOTAL_LENGTH = 3
def munge_name(name):
    '''Munges the package name field in case it is not to spec.'''
    ...

def munge_title_to_name(name):
    '''Munge a package title into a package name.'''
    ...

def substitute_ascii_equivalents(text_unicode):
    """
    This takes a UNICODE string and replaces Latin-1 characters with something
    equivalent in 7-bit ASCII. It returns a plain ASCII string. This function
    makes a best effort to convert Latin-1 characters into ASCII equivalents.
    It does not just strip out the Latin-1 characters. All characters in the
    standard 7-bit ASCII range are preserved. In the 8th bit range all the
    Latin-1 accented letters are converted to unaccented equivalents. Most
    symbol characters are converted to something meaningful. Anything not
    converted is deleted.
    """
    ...

def munge_tag(tag):
    ...

def munge_filename_legacy(filename):
    ''' Tidies a filename. NB: deprecated

    Unfortunately it mangles any path or filename extension, so is deprecated.
    It needs to remain unchanged for use by group_dictize() and
    Upload.update_data_dict() because if this routine changes then group images
    uploaded previous to the change may not be viewable.
    '''
    ...

def munge_filename(filename):
    ''' Tidies a filename

    Keeps the filename extension (e.g. .csv).
    Strips off any path on the front.

    Returns a Unicode string.
    '''
    ...

