MAX_FILENAME_EXTENSION_LENGTH = 21
MAX_FILENAME_TOTAL_LENGTH = 100
MIN_FILENAME_TOTAL_LENGTH = 3

def munge_name(name):
    ...

def munge_title_to_name(name):
    ...

def substitute_ascii_equivalents(text_unicode):
    ...

def munge_tag(tag): ...
def munge_filename_legacy(filename):
    ...

def munge_filename(filename):
    ...
