MAX_FILENAME_EXTENSION_LENGTH: int
MAX_FILENAME_TOTAL_LENGTH: int
MIN_FILENAME_TOTAL_LENGTH: int

def munge_name(name: str) -> str: ...
def munge_title_to_name(name: str) -> str: ...
def substitute_ascii_equivalents(text_unicode: str) -> str: ...
def munge_tag(tag: str) -> str: ...
def munge_filename_legacy(filename: str) -> str: ...
def munge_filename(filename: str) -> str: ...
