import logging

log = logging.getLogger(__name__)

def reset_package_plugins(): ...
def reset_group_plugins(): ...
def lookup_package_plugin(package_type=...):
    ...

def lookup_group_plugin(group_type=...):
    ...

def lookup_group_controller(group_type=...):
    ...

def lookup_group_blueprints(group_type=...):
    ...

def register_package_plugins():
    ...

def register_package_blueprints(app):
    ...

def set_default_package_plugin(): ...
def register_group_plugins():
    ...

def register_group_blueprints(app):
    ...

def set_default_group_plugin(): ...
def plugin_validate(plugin, context, data_dict, schema, action):
    ...

def get_permission_labels():
    ...

class DefaultDatasetForm(object):

    def create_package_schema(self): ...
    def update_package_schema(self): ...
    def show_package_schema(self): ...
    def setup_template_variables(self, context, data_dict): ...
    def new_template(self): ...
    def read_template(self): ...
    def edit_template(self): ...
    def search_template(self): ...
    def history_template(self): ...
    def resource_template(self): ...
    def package_form(self): ...
    def resource_form(self): ...

class DefaultGroupForm(object):

    def group_controller(self): ...
    def new_template(self):
        ...
    def index_template(self):
        ...
    def read_template(self):
        ...
    def about_template(self):
        ...
    def edit_template(self):
        ...
    def activity_template(self):
        ...
    def admins_template(self):
        ...
    def bulk_process_template(self):
        ...
    def group_form(self): ...
    def form_to_db_schema_options(self, options):
        ...
    def form_to_db_schema_api_create(self): ...
    def form_to_db_schema_api_update(self): ...
    def form_to_db_schema(self): ...
    def db_to_form_schema(self):
        ...
    def db_to_form_schema_options(self, options):
        ...
    def check_data_dict(self, data_dict):
        ...
    def setup_template_variables(self, context, data_dict): ...

class DefaultOrganizationForm(DefaultGroupForm):
    def group_controller(self): ...
    def group_form(self): ...
    def setup_template_variables(self, context, data_dict): ...
    def new_template(self): ...
    def about_template(self): ...
    def index_template(self): ...
    def admins_template(self): ...
    def bulk_process_template(self): ...
    def read_template(self): ...
    def edit_template(self): ...
    def activity_template(self): ...

class DefaultTranslation(object):
    def i18n_directory(self):
        ...
    def i18n_locales(self):
        ...
    def i18n_domain(self):
        ...

class DefaultPermissionLabels(object):
    def get_dataset_labels(self, dataset_obj): ...
    def get_user_dataset_labels(self, user_obj): ...
