"""
This type stub file was generated by pyright.
"""

import logging

u'''
Redis utilities.

.. versionadded:: 2.7
'''
log = logging.getLogger(__name__)
REDIS_URL_SETTING_NAME = u'ckan.redis.url'
REDIS_URL_DEFAULT_VALUE = u'redis://localhost:6379/0'
_connection_pool = None
def connect_to_redis():
    u'''
    (Lazily) connect to Redis.

    The connection is set up but not actually established. The latter
    happens automatically once the connection is used.

    :returns: A lazy Redis connection.
    :rtype: ``redis.Redis``

    .. seealso:: :py:func:`is_redis_available`
    '''
    ...

def is_redis_available():
    u'''
    Check whether Redis is available.

    :returns: The availability of Redis.
    :rtype: bool

    .. seealso:: :py:func:`connect_to_redis`
    '''
    ...

