def reset_template_info_cache():
    ...

def find_template(template_name):
    ...

def template_type(template_path): ...

class TemplateNotFound(Exception): ...

def template_info(template_name):
    ...
