
import cgi
import logging
from werkzeug.datastructures import FileStorage as FlaskFileStorage

ALLOWED_UPLOAD_TYPES = (cgi.FieldStorage, FlaskFileStorage)
MB = 1 << 20
log = logging.getLogger(__name__)

def get_uploader(upload_to, old_filename=...):
    ...

def get_resource_uploader(data_dict):
    ...

def get_storage_path():
    ...

def get_max_image_size(): ...
def get_max_resource_size(): ...

class Upload(object):
    def __init__(self, object_type, old_filename=...) -> None:
        ...
    def update_data_dict(self, data_dict, url_field, file_field, clear_field):
        ...
    def upload(self, max_size=...):
        ...

class ResourceUpload(object):
    def __init__(self, resource) -> None: ...
    def get_directory(self, id): ...
    def get_path(self, id): ...
    def upload(self, id, max_size=...):
        ...
