env = None

def create_library(name, path):
    ...

def webassets_init(): ...
def include_asset(name): ...
def render_assets(type_): ...
def get_webassets_path(): ...
def add_public_path(path, url): ...
