"""
This type stub file was generated by pyright.
"""

import logging

logger = logging.getLogger(__name__)
env = None
def create_library(name, path):
    """Create WebAssets library(set of Bundles).
    """
    ...

def webassets_init():
    ...

def include_asset(name):
    ...

def render_assets(type_):
    ...

def get_webassets_path():
    ...

def add_public_path(path, url):
    ...

