from typing import Optional
from markupsafe import Markup

from webassets import Environment

env: Optional[Environment]

def create_library(name: str, path: str) -> None: ...
def webassets_init() -> None: ...
def include_asset(name: str) -> None: ...
def render_assets(type_: str) -> Markup: ...
def get_webassets_path() -> str: ...
def add_public_path(path: str, url: str) -> None: ...
