"""
This type stub file was generated by pyright.
"""

import sys

__version__ = '2.10.0a'
__description__ = 'CKAN Software'
__long_description__ = '''
CKAN is the world's leading Open Source data portal platform.

It powers dozens of Open Data portals around the world, including
data.gov, open.canada.ca and europeandataportal.eu but also regional,
research and community organizations.

It makes easy to publish, share and find data online and is fully
customizable via extensions and plugins.

Check https://ckan.org to know more.
'''
__license__ = 'AGPL'
