class CkanConfigurationException(Exception): ...
class CkanException(Exception): ...
class CkanUrlException(Exception): ...
class CkanVersionException(Exception): ...
class EmptyRevisionException(CkanException): ...
class HelperError(Exception): ...
