"""
This type stub file was generated by pyright.
"""

import sys
import jinja2
import re
from __future__ import print_function
from paste.script.templates import Template, var
from paste.script.create_distro import Command

"""A Paste template for creating new CKAN extensions.

Usage::

  paster --plugin=ckan create -t ckanext

See:

* http://docs.pylonsproject.org/projects/pylons-webframework/en/latest/advanced_pylons/creating_paste_templates.html
* http://pythonpaste.org/script/developer.html#templates

"""

def jinja2_template_renderer(
    content_as_string, vars_as_dict, filename=...
): ...

class CkanextTemplate(Template):
    """A Paste template for a skeleton CKAN extension package."""

    _template_dir = ...
    summary = ...
    use_cheetah = ...
    template_renderer = ...
    vars = ...
    def check_vars(self, vars, cmd): ...
