from ckan.types import ErrorDict
from ckan import model
from ckan.model.domain_object import DomainObject
from typing import Dict, Mapping

def rename_keys(
    dict_: Dict, key_map: Mapping, reverse: bool = ..., destructive: bool = ...
) -> Dict: ...
def get_domain_object(
    model: model, domain_object_ref: str
) -> DomainObject: ...
def error_summary(error_dict: ErrorDict) -> Dict[str, str]: ...
