from typing import List
from ckan.logic import Context, DataDict

def user_delete(context: Context, data_dict: DataDict) -> None: ...
def package_delete(context: Context, data_dict: DataDict) -> None: ...
def dataset_purge(context: Context, data_dict: DataDict) -> None: ...
def resource_delete(context: Context, data_dict: DataDict) -> None: ...
def resource_view_delete(context: Context, data_dict: DataDict) -> None: ...
def resource_view_clear(context: Context, data_dict: DataDict) -> None: ...
def package_relationship_delete(
    context: Context, data_dict: DataDict
) -> None: ...
def member_delete(context: Context, data_dict: DataDict) -> None: ...
def package_collaborator_delete(
    context: Context, data_dict: DataDict
) -> None: ...
def group_delete(context: Context, data_dict: DataDict) -> None: ...
def organization_delete(context: Context, data_dict: DataDict) -> None: ...
def group_purge(context: Context, data_dict: DataDict) -> None: ...
def organization_purge(context: Context, data_dict: DataDict) -> None: ...
def task_status_delete(context: Context, data_dict: DataDict) -> None: ...
def vocabulary_delete(context: Context, data_dict: DataDict) -> None: ...
def tag_delete(context: Context, data_dict: DataDict) -> None: ...
def unfollow_user(context: Context, data_dict: DataDict) -> None: ...
def unfollow_dataset(context: Context, data_dict: DataDict) -> None: ...
def _group_or_org_member_delete(
    context: Context, data_dict: DataDict
) -> None: ...
def group_member_delete(context: Context, data_dict: DataDict) -> None: ...
def organization_member_delete(
    context: Context, data_dict: DataDict
) -> None: ...
def unfollow_group(context: Context, data_dict: DataDict) -> None: ...
def job_clear(context: Context, data_dict: DataDict) -> List[str]: ...
def job_cancel(context: Context, data_dict: DataDict) -> None: ...
def api_token_revoke(context: Context, data_dict: DataDict) -> None: ...
