from typing import Any, Dict, Iterable, Tuple, Union
from routes import request_config as routes_request_config

def make_app(conf: Dict) -> Any: ...

class AskAppDispatcherMiddleware(object):
    def __init__(self, apps: Dict) -> None: ...
    def ask_around(
        self, environ: Any
    ) -> Iterable[Union[Tuple[bool, str], Tuple[bool, str, str]]]: ...
    def __call__(self, environ: Any, start_response: Any): ...
