"""
This type stub file was generated by pyright.
"""

"""Common middleware used by both Flask and Pylons app stacks."""

class RootPathMiddleware(object):
    """
    Prevents the SCRIPT_NAME server variable conflicting with the ckan.root_url
    config. The routes package uses the SCRIPT_NAME variable and appends to the
    path and ckan addes the root url causing a duplication of the root path.

    This is a middleware to ensure that even redirects use this logic.
    """

    def __init__(self, app, config) -> None: ...
    def __call__(self, environ, start_response): ...

class CloseWSGIInputMiddleware(object):
    """
    webob.request.Request has habit to create FakeCGIBody. This leads(
    during file upload) to creating temporary files that are not closed.
    For long lived processes this means that for each upload you will
    spend the same amount of temporary space as size of uploaded
    file additionally, until server restart(this will automatically
    close temporary files).

    This middleware is supposed to close such files after each request.
    """

    def __init__(self, app, config) -> None: ...
    def __call__(self, environ, start_response): ...

class TrackingMiddleware(object):
    def __init__(self, app, config) -> None: ...
    def __call__(self, environ, start_response): ...

class HostHeaderMiddleware(object):
    """
    Prevent the `Host` header from the incoming request to be used
    in the `Location` header of a redirect.
    """

    def __init__(self, app) -> None: ...
    def __call__(self, environ, start_response): ...
