"""
This type stub file was generated by pyright.
"""

import sys
import os
import click
import logging
from logging.config import fileConfig as loggingFileConfig
from six.moves.configparser import ConfigParser
from ckan.exceptions import CkanConfigurationException

log = logging.getLogger(__name__)
class CKANConfigLoader(object):
    def __init__(self, filename) -> None:
        ...
    
    def get_config(self):
        ...
    


def error_shout(exception):
    ...

def load_config(ini_path=...):
    ...

