from typing import Union
from flask.blueprints import Blueprint
from flask.views import MethodView
from flask.wrappers import Response

admin: Blueprint

def before_request() -> None: ...
def index() -> str: ...

class ResetConfigView(MethodView):
    def get(self) -> Union[str, Response]: ...
    def post(self) -> Response: ...

class ConfigView(MethodView):
    def get(self) -> str: ...
    def post(self) -> Union[str, Response]: ...

class TrashView(MethodView):
    def get(self) -> str: ...
    def post(self) -> Response: ...
