from typing import Dict, Union

from flask.blueprints import Blueprint
from flask.wrappers import Response

CONTENT_TYPES = Dict[str, str]

API_REST_DEFAULT_VERSION: int

API_DEFAULT_VERSION: int
API_MAX_VERSION: int

api: Blueprint

def action(logic_function: str, ver: int = ...) -> Response: ...
def get_api(ver: int = ...) -> Response: ...
def dataset_autocomplete(ver: int = ...) -> Response: ...
def tag_autocomplete(ver: int = ...) -> Response: ...
def format_autocomplete(ver: int = ...) -> Response: ...
def user_autocomplete(ver: int = ...) -> Response: ...
def group_autocomplete(ver: int = ...) -> Response: ...
def organization_autocomplete(ver: int = ...) -> Response: ...
def snippet(snippet_path: str, ver: int = ...) -> str: ...
def i18n_js_translations(
    lang: str, ver: int = ...
) -> Union[str, Response]: ...
