from flask.blueprints import Blueprint

dashboard: Blueprint

def before_request() -> None: ...
def index(offset: int = ...) -> str: ...
def datasets() -> str: ...
def organizations() -> str: ...
def groups() -> str: ...
