"""
This type stub file was generated by pyright.
"""

from flask import Blueprint

CACHE_PARAMETERS = [u'__cache', u'__no_cache__']
home = Blueprint(u'home', __name__)
@home.before_request
def before_request():
    u'''set context and check authorization'''
    ...

def index():
    u'''display home page'''
    ...

def about():
    u''' display about page'''
    ...

util_rules = [(u'/', index), (u'/about', about)]
