"""
This type stub file was generated by pyright.
"""

import logging

log = logging.getLogger(__name__)
class SearchIndexError(Exception):
    ...


class SearchError(Exception):
    ...


class SearchQueryError(SearchError):
    ...


DEFAULT_SOLR_URL = 'http://127.0.0.1:8983/solr'
class SolrSettings(object):
    _is_initialised = ...
    _url = ...
    _user = ...
    _password = ...
    @classmethod
    def init(cls, url, user=..., password=...):
        ...
    
    @classmethod
    def get(cls):
        ...
    


def is_available():
    """
    Return true if we can successfully connect to Solr.
    """
    ...

def make_connection(decode_dates=...):
    ...

def solr_datetime_decoder(d):
    ...

