from typing import Dict, Optional, Tuple

from pysolr import Solr

DEFAULT_SOLR_URL: str

class SearchError(Exception): ...
class SearchIndexError(Exception): ...
class SearchQueryError(SearchError): ...

class SolrSettings:
    @classmethod
    def get(cls) -> Tuple[str, str, str]: ...
    @classmethod
    def init(
        cls, url: str, user: Optional[str], password: Optional[str]
    ) -> None: ...

def is_available() -> bool: ...
def make_connection(decode_dates: bool) -> Solr: ...
def solr_datetime_decoder(d: Dict) -> Dict: ...
