"""
This type stub file was generated by pyright.
"""

log = __import__('logging').getLogger(__name__)
class State(object):
    ACTIVE = ...
    DELETED = ...
    PENDING = ...


class StatefulObjectMixin(object):
    __stateful__ = ...
    def delete(self):
        ...
    
    def undelete(self):
        ...
    
    def is_active(self):
        ...
    


