"""
This type stub file was generated by pyright.
"""

from sqlalchemy import Column, ForeignKey, Table, types
from ckan.model import core, domain_object, meta, types as _types

group_extra_table = Table(
    "group_extra",
    meta.metadata,
    Column(
        "id", types.UnicodeText, primary_key=True, default=_types.make_uuid
    ),
    Column("group_id", types.UnicodeText, ForeignKey("group.id")),
    Column("key", types.UnicodeText),
    Column("value", types.UnicodeText),
    Column("state", types.UnicodeText, default=core.State.ACTIVE),
)

class GroupExtra(core.StatefulObjectMixin, domain_object.DomainObject): ...
