"""
This type stub file was generated by pyright.
"""

import sqlalchemy as sa
from ckan.model import domain_object, meta, types as _types

resource_view_table = sa.Table(
    "resource_view",
    meta.metadata,
    sa.Column(
        "id", sa.types.UnicodeText, primary_key=True, default=_types.make_uuid
    ),
    sa.Column(
        "resource_id", sa.types.UnicodeText, sa.ForeignKey("resource.id")
    ),
    sa.Column("title", sa.types.UnicodeText, nullable=True),
    sa.Column("description", sa.types.UnicodeText, nullable=True),
    sa.Column("view_type", sa.types.UnicodeText, nullable=False),
    sa.Column("order", sa.types.Integer, nullable=False),
    sa.Column("config", _types.JsonDictType),
)

class ResourceView(domain_object.DomainObject):
    @classmethod
    def get(cls, reference):
        """Returns a ResourceView object referenced by its id."""
        ...
    @classmethod
    def get_columns(cls): ...
    @classmethod
    def get_count_not_in_view_types(cls, view_types):
        """Returns the count of ResourceView not in the view types list"""
        ...
    @classmethod
    def delete_not_in_view_types(cls, view_types):
        """Delete the Resource Views not in the received view types list"""
        ...
    @classmethod
    def delete_all(cls, view_types=...):
        """Delete all Resource Views, or all of a particular type"""
        ...
