"""
This type stub file was generated by pyright.
"""

from sqlalchemy import Column, Table, types
from ckan.model import core, domain_object, meta

'''
The system_info table and SystemInfo mapped class store runtime-editable
configuration options.

For more details, check :doc:`maintaining/configuration`.
'''
system_info_table = Table('system_info', meta.metadata, Column('id', types.Integer(), primary_key=True, nullable=False), Column('key', types.Unicode(100), unique=True, nullable=False), Column('value', types.UnicodeText), Column('state', types.UnicodeText, default=core.State.ACTIVE))
class SystemInfo(core.StatefulObjectMixin, domain_object.DomainObject):
    def __init__(self, key, value) -> None:
        ...
    


def get_system_info(key, default=...):
    ''' get data from system_info table '''
    ...

def delete_system_info(key, default=...):
    ''' delete data from system_info table '''
    ...

def set_system_info(key, value):
    ''' save data in the system_info table '''
    ...

