"""
This type stub file was generated by pyright.
"""

from sqlalchemy import Column, Table
from sqlalchemy.types import UnicodeText
from ckan.model import meta

term_translation_table = Table(
    "term_translation",
    meta.metadata,
    Column("term", UnicodeText, nullable=False),
    Column("term_translation", UnicodeText, nullable=False),
    Column("lang_code", UnicodeText, nullable=False),
)
