"""
This type stub file was generated by pyright.
"""

from sqlalchemy import Column, Table, types
from ckan.model import domain_object, meta

tracking_raw_table = Table('tracking_raw', meta.metadata, Column('user_key', types.Unicode(100), nullable=False), Column('url', types.UnicodeText, nullable=False), Column('tracking_type', types.Unicode(10), nullable=False), Column('access_timestamp', types.DateTime))
tracking_summary_table = Table('tracking_summary', meta.metadata, Column('url', types.UnicodeText, primary_key=True, nullable=False), Column('package_id', types.UnicodeText), Column('tracking_type', types.Unicode(10), nullable=False), Column('count', types.Integer, nullable=False), Column('running_total', types.Integer, nullable=False), Column('recent_views', types.Integer, nullable=False), Column('tracking_date', types.DateTime))
class TrackingSummary(domain_object.DomainObject):
    @classmethod
    def get_for_package(cls, package_id):
        ...
    
    @classmethod
    def get_for_resource(cls, url):
        ...
    


