from datetime import datetime
from typing import Union
from sqlalchemy import types

def make_uuid() -> str: ...

class UuidType(types.TypeDecorator): ...
class JsonType(types.TypeDecorator): ...
class JsonDictType(JsonType): ...

def iso_date_to_datetime_for_sqlite(
    datetime_or_iso_date_if_sqlite: Union[datetime, str]
) -> datetime: ...
