"""
This type stub file was generated by pyright.
"""

from sqlalchemy import Column, Table, types
from ckan.model import domain_object, meta, types as _types

VOCABULARY_NAME_MIN_LENGTH = 2
VOCABULARY_NAME_MAX_LENGTH = 100
vocabulary_table = Table(
    "vocabulary",
    meta.metadata,
    Column(
        "id", types.UnicodeText, primary_key=True, default=_types.make_uuid
    ),
    Column(
        "name",
        types.Unicode(VOCABULARY_NAME_MAX_LENGTH),
        nullable=False,
        unique=True,
    ),
)

class Vocabulary(domain_object.DomainObject):
    def __init__(self, name) -> None: ...
    @classmethod
    def get(cls, id_or_name):
        """Return a Vocabulary object referenced by its id or name, or
        None if there is no vocabulary with the given id or name."""
        ...
    @property
    def tags(self): ...
