"""
This type stub file was generated by pyright.
"""

import datetime
import sqlalchemy
import six
from sqlalchemy.orm import class_mapper
from six import text_type
from ckan.model.core import State

legacy_dict_sort = lambda x: (len(x), dict.items(x))
def table_dictize(obj, context, **kw):
    '''Get any model object and represent it as a dict'''
    ...

def obj_list_dictize(obj_list, context, sort_key=...):
    '''Get a list of model object and represent it as a list of dicts'''
    ...

def obj_dict_dictize(obj_dict, context, sort_key=...):
    '''Get a dict whose values are model objects
    and represent it as a list of dicts'''
    ...

def get_unique_constraints(table, context):
    '''Get a list of unique constraints for a sqlalchemy table'''
    ...

def table_dict_save(table_dict, ModelClass, context, extra_attrs=...):
    '''Given a dict and a model class, update or create a sqlalchemy object.
    This will use an existing object if "id" is supplied OR if any unique
    constraints are met. e.g supplying just a tag name will get out that tag obj.
    '''
    ...

