from ckan.types import Context, AuthResult
from ckan import model

def get_package_object(context: Context, data_dict=None) -> model.Package: ...
def get_resource_object(
    context: Context, data_dict=None
) -> model.Resource: ...
def get_group_object(context: Context, data_dict=None) -> model.Group: ...
def get_user_object(context: Context, data_dict=None) -> model.User: ...
def get_activity_object(
    context: Context, data_dict=None
) -> model.Activity: ...
def restrict_anon(context: Context) -> AuthResult: ...
