from ckan.logic import Context, DataDict, AuthResult

def user_delete(context: Context, data_dict: DataDict) -> AuthResult: ...
def package_delete(context: Context, data_dict: DataDict) -> AuthResult: ...
def dataset_purge(context: Context, data_dict: DataDict) -> AuthResult: ...
def resource_delete(context: Context, data_dict: DataDict) -> AuthResult: ...
def resource_view_delete(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def resource_view_clear(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def package_relationship_delete(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def group_delete(context: Context, data_dict: DataDict) -> AuthResult: ...
def group_purge(context: Context, data_dict: DataDict) -> AuthResult: ...
def organization_purge(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def organization_delete(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def revision_undelete(context: Context, data_dict: DataDict) -> AuthResult: ...
def revision_delete(context: Context, data_dict: DataDict) -> AuthResult: ...
def task_status_delete(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def vocabulary_delete(context: Context, data_dict: DataDict) -> AuthResult: ...
def tag_delete(context: Context, data_dict: DataDict) -> AuthResult: ...
def group_member_delete(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def organization_member_delete(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def member_delete(context: Context, data_dict: DataDict) -> AuthResult: ...
def package_collaborator_delete(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def job_clear(context: Context, data_dict: DataDict) -> AuthResult: ...
def job_cancel(context: Context, data_dict: DataDict) -> AuthResult: ...
def api_token_revoke(context: Context, data_dict: DataDict) -> AuthResult: ...
