from ckan.types import Context, DataDict, AuthResult

def sysadmin(context: Context, data_dict: DataDict) -> AuthResult: ...
def site_read(context: Context, data_dict: DataDict) -> AuthResult: ...
def package_search(context: Context, data_dict: DataDict) -> AuthResult: ...
def package_list(context: Context, data_dict: DataDict) -> AuthResult: ...
def current_package_list_with_resources(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def group_list(context: Context, data_dict: DataDict) -> AuthResult: ...
def group_list_authz(context: Context, data_dict: DataDict) -> AuthResult: ...
def group_list_available(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def organization_list(context: Context, data_dict: DataDict) -> AuthResult: ...
def organization_list_for_user(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def license_list(context: Context, data_dict: DataDict) -> AuthResult: ...
def vocabulary_list(context: Context, data_dict: DataDict) -> AuthResult: ...
def tag_list(context: Context, data_dict: DataDict) -> AuthResult: ...
def user_list(context: Context, data_dict: DataDict) -> AuthResult: ...
def package_relationships_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def package_show(context: Context, data_dict: DataDict) -> AuthResult: ...
def resource_show(context: Context, data_dict: DataDict) -> AuthResult: ...
def resource_view_show(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def resource_view_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def group_show(context: Context, data_dict: DataDict) -> AuthResult: ...
def organization_show(context: Context, data_dict: DataDict) -> AuthResult: ...
def vocabulary_show(context: Context, data_dict: DataDict) -> AuthResult: ...
def tag_show(context: Context, data_dict: DataDict) -> AuthResult: ...
def user_show(context: Context, data_dict: DataDict) -> AuthResult: ...
def package_autocomplete(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def group_autocomplete(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def organization_autocomplete(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def tag_autocomplete(context: Context, data_dict: DataDict) -> AuthResult: ...
def user_autocomplete(context: Context, data_dict: DataDict) -> AuthResult: ...
def format_autocomplete(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def task_status_show(context: Context, data_dict: DataDict) -> AuthResult: ...
def get_site_user(context: Context, data_dict: DataDict) -> AuthResult: ...
def member_roles_list(context: Context, data_dict: DataDict) -> AuthResult: ...
def dashboard_activity_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def dashboard_new_activities_count(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def activity_list(context: Context, data_dict: DataDict) -> AuthResult: ...
def user_activity_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def package_activity_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def group_activity_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def organization_activity_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def activity_show(context: Context, data_dict: DataDict) -> AuthResult: ...
def activity_data_show(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def activity_diff(context: Context, data_dict: DataDict) -> AuthResult: ...
def user_follower_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def dataset_follower_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def group_follower_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def organization_follower_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def _followee_list(context: Context, data_dict: DataDict) -> AuthResult: ...
def followee_list(context: Context, data_dict: DataDict) -> AuthResult: ...
def user_followee_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def dataset_followee_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def group_followee_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def organization_followee_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def user_reset(context: Context, data_dict: DataDict) -> AuthResult: ...
def request_reset(context: Context, data_dict: DataDict) -> AuthResult: ...
def help_show(context: Context, data_dict: DataDict) -> AuthResult: ...
def config_option_show(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def config_option_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def job_list(context: Context, data_dict: DataDict) -> AuthResult: ...
def job_show(context: Context, data_dict: DataDict) -> AuthResult: ...
def api_token_list(context: Context, data_dict: DataDict) -> AuthResult: ...
def package_collaborator_list(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
def package_collaborator_list_for_user(
    context: Context, data_dict: DataDict
) -> AuthResult: ...
